# Generated by Django 2.1.7 on 2019-03-26 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicstreamer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('office', 'office'), ('gym', 'gym'), ('canteen', 'canteen'), ('library', 'library'), ('travel', 'travel')], max_length=64, verbose_name='Location')),
                ('weather', models.CharField(choices=[('sunny', 'sunny'), ('cloudy', 'cloudy'), ('rain', 'rain')], max_length=64, verbose_name='Weather')),
                ('music_rank', models.IntegerField(default=0, verbose_name='Music Rank')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='frame_0',
            field=models.IntegerField(default=0, verbose_name='Frame 0'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_1',
            field=models.IntegerField(default=0, verbose_name='Frame 1'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_2',
            field=models.IntegerField(default=0, verbose_name='Frame 2'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_3',
            field=models.IntegerField(default=0, verbose_name='Frame 3'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_4',
            field=models.IntegerField(default=0, verbose_name='Frame 4'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_5',
            field=models.IntegerField(default=0, verbose_name='Frame 5'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_6',
            field=models.IntegerField(default=0, verbose_name='Frame 6'),
        ),
        migrations.AddField(
            model_name='music',
            name='num_frames',
            field=models.IntegerField(default=0, verbose_name='Number of Frames'),
        ),
        migrations.AddField(
            model_name='music',
            name='tempo',
            field=models.FloatField(default=0, verbose_name='Tempo'),
        ),
        migrations.AddField(
            model_name='history',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='musicstreamer.Music'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
    ]
