# Generated by Django 2.1.7 on 2019-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstreamer', '0002_auto_20190326_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='tempo',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=21, verbose_name='Tempo'),
        ),
    ]
