# Generated by Django 2.2 on 2019-05-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstreamer', '0003_auto_20190414_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='frame_10',
            field=models.IntegerField(default=0, verbose_name='Frame 10'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_7',
            field=models.IntegerField(default=0, verbose_name='Frame 7'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_8',
            field=models.IntegerField(default=0, verbose_name='Frame 8'),
        ),
        migrations.AddField(
            model_name='music',
            name='frame_9',
            field=models.IntegerField(default=0, verbose_name='Frame 9'),
        ),
        migrations.AlterField(
            model_name='history',
            name='weather',
            field=models.CharField(choices=[('clear', 'clear'), ('cloudy', 'cloudy'), ('rain', 'rain')], max_length=64, verbose_name='Weather'),
        ),
    ]
